name: GildorymClasses
author: [Lucariatias, melodichand, Hohahihehu]
version: 1.0
main: com.gildorymrp.gildorymclasses.GildorymClasses
depend: [Gildorym]
commands:
    addexp:
        description: Adds exp to a player
        usage: /<command> [ign] [amount]
    checkexp:
        description: Allows a player to check their exp
        usage: /<command>
    getclass:
        description: Gets someones class
        usage: /<command> (ign)
    getlevel:
        description: Gets someones level
        usage: /<command> (ign)
    getprofession:
        description: Gets someones profession
        usage: /<command> (ign)
    listclasses:
        description: Lists the available classes
        usage: /<command>
    listprofessions:
        description: Lists the available professions
        usage: /<command>
    setclass:
        description: Sets your or someone elses class
        usage: /<command> (player) [class]
    setlevel:
        description: Sets your or someone elses level
        usage: /<command> (player) [level]
    setprofession:
        description: Sets your or someone elses profession
        usage: /<command> (player) [profession]
permissions:
    basicchar.command.addexp:
        description: Allows you to add exp
        default: op
    basicchar.command.getclass:
        description: Allows you to get other peoples classes
        default: op
    basicchar.command.getlevel:
        description: Allows you to get other peoples levels
        default: op
    basicchar.command.getprofession:
        description: Allows you to get other peoples professions
        default: op
    basicchar.command.setclass:
        description: Allows you to set other peoples classes
        default: op
    basicchar.command.setlevel:
        description: Allows you to set levels
        default: op
    basicchar.command.setprofession:
        description: Allows you to set other peoples professions
        default: op
